// Stage 3 — WRITE_COVER_LETTER. The prompt builder is fully implemented; the
// Claude call is a clearly-marked skeleton. Prose template mirror lives in
// prompts/write_cover_letter.md.

import { readFile } from "node:fs/promises";
import type { BaseResume, ParsedJob, Story, StoryBank } from "./types.js";
import { extractEmphasisTerms } from "./tailor_resume.js";

export async function loadStoryBank(path = "./story_bank.json"): Promise<StoryBank> {
  const raw = await readFile(path, "utf8");
  return JSON.parse(raw) as StoryBank;
}

/**
 * Picks the single most relevant story for a job, by tag/keyword overlap.
 * Returns the first story as a fallback if nothing matches.
 */
export function pickStory(bank: StoryBank, emphasize: string[]): Story | undefined {
  if (bank.stories.length === 0) return undefined;
  const scored = bank.stories.map((s) => {
    const hay = (s.tags ?? []).map((t) => t.toLowerCase());
    const score = emphasize.reduce(
      (acc, term) => acc + (hay.includes(term.toLowerCase()) ? 1 : 0),
      0,
    );
    return { story: s, score };
  });
  scored.sort((a, b) => b.score - a.score);
  return scored[0].story;
}

/**
 * A short summary of the tailored resume's top achievements, fed to the letter.
 * Pulls the top bullets from the (already reordered) tailored resume.
 */
export function summarizeTopAchievements(tailored: BaseResume, max = 4): string {
  const bullets: string[] = [];
  for (const exp of tailored.experience) {
    for (const b of exp.bullets) {
      bullets.push(`- ${b.text} (${exp.title}, ${exp.company})`);
      if (bullets.length >= max) return bullets.join("\n");
    }
  }
  return bullets.join("\n");
}

// ---------------------------------------------------------------------------
// Prompt
// ---------------------------------------------------------------------------

export function buildCoverLetterPrompt(
  job: ParsedJob,
  tailoredResumeSummary: string,
  story: Story | undefined,
): string {
  return `Write a concise, sincere cover letter. Output ONLY the letter body
(no date, no address block, no commentary). 3-5 short paragraphs, max ~250 words.

# JOB
Company: ${job.company}
Title: ${job.job_title}
Location: ${job.location}
Job description:
"""
${job.description}
"""

# CANDIDATE'S TOP RELEVANT ACHIEVEMENTS
${tailoredResumeSummary}

# STORY TO WEAVE IN (use this concrete anecdote, lightly edited to fit)
${story ? `${story.title}: ${story.body}` : "(no story available — use the achievements above instead)"}

# INSTRUCTIONS
- Paragraph 1: a specific hook referencing ${job.company} and the ${job.job_title} role — show you understand what they need. No generic flattery.
- Middle: tell the ONE concrete story above, tying it to a requirement in the posting.
- Keep claims truthful; do not invent facts.
- Close: short and direct — express interest and a clear, low-pressure next step.
- Plain prose. No bullet points. No "To Whom It May Concern".`;
}

// ---------------------------------------------------------------------------
// WRITE_COVER_LETTER(job, tailored_resume_summary, story_bank) -> text (SKELETON)
// ---------------------------------------------------------------------------

export async function WRITE_COVER_LETTER(
  job: ParsedJob,
  tailoredResumeSummary: string,
  storyBank: StoryBank,
): Promise<string> {
  const emphasize = extractEmphasisTerms(job.description);
  const story = pickStory(storyBank, emphasize);
  const prompt = buildCoverLetterPrompt(job, tailoredResumeSummary, story);

  // Generated by the routine itself; wire the SDK (see tailor_resume.ts) to run standalone.
  throw new Error("WRITE_COVER_LETTER runs via the routine; wire the SDK to use standalone. Prompt:\n" + prompt.slice(0, 200) + "...");
}
